### ISSUE TITLE
Output with supporting sequence IDs

### ISSUE THREAD

**Issue by kleii** [uma-pi1/mgfsm#2]
I was browsing through the code but could not really pinpoint the place where I could potentially collect the supporting sequence IDs for each frequent pattern (and output them).

Is this possible to do in the algorithm (without too much effort)? If yes, where could I potentially start?

**Comment by kbeedkar** [comment]
It will be quite some effort if you are running MGFSM in distributed mode. In the sequential mode, its quite straightforward: In BfsMiner, you can get sequence ids from the posting list of each frequent sequence.

**Comment by kleii** [comment]
I was in fact interested in the distributed mode. Thanks anyway.
