### ISSUE TITLE
Does this tool support non-English languages?

### ISSUE THREAD

**Issue by HuengchI** [uma-pi1/mgfsm#6]
Will this tool work with non-English text inputs? Do I need to modify the tokenization or make any other adjustments?

**Comment by kbeedkar** [comment]
It should work as long the input is in the expected sequence format.

**Comment by HuengchI** [comment]
@kbeedkar 
Thank you for your kind response. I have encountered some issues while testing the program with arguments `-s 1 -g 10 -l 10` on my data. The program seems to be recognizing continuous characters with `str_len > 10` as a single English word.  In English, words are typically separated by spaces, but this may not hold true for non-English languages. This behavior could potentially result in sentences being incorrectly identified as single words.

The current output shows sentences like:

```text
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This the 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This information 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This in 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This can 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This be 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This inferred 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This from 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This given 	1
"乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。 This contract." 	1
```
All these entries share a common **"word"** `乙方委派李x3负责合同履行、工程质量、办理验收、变更等事宜。` with `str_len` equaling to `30`.

However, I am aiming for an output similar to:
```text
"乙方委派李x3负责合" 	1
```
In the desired output, the word sequence `乙方委派李x3负责合` with a `str_len` of `10` appears only `once` in my input text collection, and the support value appropriately reflects this occurrence.
